-- vim.g.catppuccin_flavour = "macchiato" -- latte, frappe, macchiato, mocha
-- require("catppuccin").setup {
--   styles = {
--     comments = { "italic" },
--     conditionals = { "italic" },
--     loops = { "italic", "bold" },
--     functions = { "bold" },
--     keywords = { "italic", "bold" },
--     strings = { "italic" },
--     variables = {},
--     numbers = {},
--     booleans = { "italic" },
--     properties = { "bold" },
--     types = { "bold" },
--     operators = { "bold" },
--   },
-- }
-- vim.cmd [[colorscheme catppuccin]]
-- require('nvim-tundra').setup({
--   transparent_background = false,
--   editor = {
--     search = {},
--     substitute = {},
--   },
--   syntax = {
--     booleans = { bold = true, italic = true },
--     comments = { bold = true, italic = true },
--     conditionals = {},
--     constants = { bold = true },
--     functions = {},
--     keywords = {},
--     loops = {},
--     numbers = { bold = true },
--     operators = { bold = true },
--     punctuation = {},
--     strings = {},
--     types = { italic = true },
--   },
--   diagnostics = {
--     errors = {},
--     warnings = {},
--     information = {},
--     hints = {},
--   },
--   plugins = {
--     lsp = true,
--     treesitter = true,
--     cmp = true,
--     context = true,
--     dbui = true,
--     gitsigns = true,
--     telescope = true,
--   },
--   overwrite = {
--     colors = {},
--     highlights = {},
--   },
-- })
--
-- vim.opt.background = 'dark'
-- vim.cmd('colorscheme tundra')
-- highlight function arguments, call after setting colorscheme to make sure nothing is overriden
require"colorbuddy".colorscheme('cobalt2')
require"hlargs".setup()
-- require"trld".setup{position = "top"}
